
export const USER_ACTION_TYPES={
    SIGNIN_START:'SIGNIN_START',
    SIGNIN_SUCCESSED:'SIGNIN_SUCCESSFULLY',
    SIGNIN_FAILED:'SIGNIN_FAILED',
    SIGNUP_START:'SIGNUP_START',
    SIGNUP_SUCCESSED:'SIGNUP_SUCCESSFULLY',
    SIGNUP_FAILED:'SIGNUP_FAILED',
    SIGNOUT_START:'SIGNOUT_START',
    UPDATE_USER_PROFILE:'UPDATE_USER_PROFILE',
    UPDATE_PROFILE_START:'UPDATE_PROFILE_START'
}